name: Deploy Orquídea a Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Obtener el código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Compilar la aplicación
        run: npm run build

      - name: Desplegar a Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 217.196.54.114
          username: u998920878.miorquidea.com
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./dist/
          server-dir: /public_html/
